-- CATAN AMIGOS — Supabase schema
-- Score Amigos: (número de jugadores - posición final) × multiplicador
-- Multiplicadores: 3 jugadores = 1.0 | 4 = 1.2 | 5 = 1.3 | 6 = 1.5

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  played_at date not null default current_date,
  player_count integer not null check (player_count between 3 and 6),
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  position integer not null check (position between 1 and 6),
  created_at timestamptz not null default now(),
  unique (game_id, player_id),
  unique (game_id, position)
);

create or replace view public.game_result_scores as
select
  gr.id,
  gr.game_id,
  gr.player_id,
  gr.position,
  g.season_id,
  g.played_at,
  g.player_count,
  (g.player_count - gr.position) *
    case g.player_count
      when 3 then 1.0
      when 4 then 1.2
      when 5 then 1.3
      when 6 then 1.5
    end as score_amigos,
  case when gr.position = 1 then 1 else 0 end as win
from public.game_results gr
join public.games g on g.id = gr.game_id;

create or replace view public.season_standings as
select
  g.season_id,
  p.id as player_id,
  p.name,
  coalesce(sum(grs.score_amigos), 0)::numeric(10,2) as score_amigos,
  count(grs.id)::integer as games_played,
  coalesce(sum(grs.win), 0)::integer as wins,
  round(avg(grs.position)::numeric, 2) as average_position
from public.players p
left join public.game_result_scores grs on grs.player_id = p.id
left join public.games g on g.id = grs.game_id
where g.season_id is not null
group by g.season_id, p.id, p.name;

-- Initial permissions for the public app.
-- We will tighten these with RLS once the app's write flow is connected.
alter table public.seasons enable row level security;
alter table public.players enable row level security;
alter table public.games enable row level security;
alter table public.game_results enable row level security;

create policy "public read seasons" on public.seasons for select using (true);
create policy "public read players" on public.players for select using (true);
create policy "public read games" on public.games for select using (true);
create policy "public read results" on public.game_results for select using (true);

create policy "public insert seasons" on public.seasons for insert with check (true);
create policy "public insert players" on public.players for insert with check (true);
create policy "public insert games" on public.games for insert with check (true);
create policy "public insert results" on public.game_results for insert with check (true);
