-- CATAN AMIGOS — Supabase schema
-- Score Amigos = (N - Puesto Final) × multiplicador
-- 3 jugadores = 1.0 | 4 = 1.2 | 5 = 1.3 | 6 = 1.5

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  season_id bigint not null references public.seasons(id) on delete cascade,
  played_at date not null default current_date,
  player_count integer not null check (player_count between 3 and 6),
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  position integer not null check (position between 1 and 6),
  victory_points integer check (victory_points is null or victory_points between 0 and 30),
  created_at timestamptz not null default now(),
  unique (game_id, player_id),
  unique (game_id, position)
);

alter table public.games add column if not exists legacy_id integer;
alter table public.game_results add column if not exists victory_points integer;
create unique index if not exists games_legacy_id_uidx on public.games(legacy_id) where legacy_id is not null;

create index if not exists games_season_id_idx on public.games(season_id);
create index if not exists games_played_at_idx on public.games(played_at desc);
create index if not exists game_results_game_id_idx on public.game_results(game_id);
create index if not exists game_results_player_id_idx on public.game_results(player_id);

create or replace view public.game_result_scores with (security_invoker = true) as
select gr.id, gr.game_id, gr.player_id, gr.position, gr.victory_points,
  g.season_id, g.played_at, g.player_count,
  round(((g.player_count-gr.position)*case g.player_count when 3 then 1.0 when 4 then 1.2 when 5 then 1.3 when 6 then 1.5 end)::numeric,2) as score_amigos,
  case when gr.position=1 then 1 else 0 end as win,
  case when gr.position=g.player_count then 1 else 0 end as last_place
from public.game_results gr join public.games g on g.id=gr.game_id;

-- El Excel ordena el ranking por Score Amigos promedio, no por acumulado.
create or replace view public.season_standings with (security_invoker = true) as
select g.season_id,p.id as player_id,p.name,
  round(coalesce(sum(grs.score_amigos),0)::numeric,2) as score_amigos_total,
  round(coalesce(avg(grs.score_amigos),0)::numeric,2) as score_amigos_avg,
  count(grs.id)::integer as games_played,
  coalesce(sum(grs.win),0)::integer as wins,
  coalesce(sum(grs.last_place),0)::integer as last_places,
  round((100.0*coalesce(sum(grs.win),0)/nullif(count(grs.id),0))::numeric,1) as win_rate,
  round((100.0*coalesce(sum(grs.last_place),0)/nullif(count(grs.id),0))::numeric,1) as last_place_rate,
  round(avg(grs.position)::numeric,2) as average_position,
  round(avg(grs.victory_points)::numeric,2) as average_victory_points
from public.game_result_scores grs join public.games g on g.id=grs.game_id join public.players p on p.id=grs.player_id
group by g.season_id,p.id,p.name;

create or replace view public.all_time_standings with (security_invoker = true) as
select p.id as player_id,p.name,
  round(coalesce(sum(grs.score_amigos),0)::numeric,2) as score_amigos_total,
  round(coalesce(avg(grs.score_amigos),0)::numeric,2) as score_amigos_avg,
  count(grs.id)::integer as games_played,
  coalesce(sum(grs.win),0)::integer as wins,
  coalesce(sum(grs.last_place),0)::integer as last_places,
  round((100.0*coalesce(sum(grs.win),0)/nullif(count(grs.id),0))::numeric,1) as win_rate,
  round((100.0*coalesce(sum(grs.last_place),0)/nullif(count(grs.id),0))::numeric,1) as last_place_rate,
  round(avg(grs.position)::numeric,2) as average_position,
  round(avg(grs.victory_points)::numeric,2) as average_victory_points
from public.players p left join public.game_result_scores grs on grs.player_id=p.id
group by p.id,p.name;

alter table public.seasons enable row level security;
alter table public.players enable row level security;
alter table public.games enable row level security;
alter table public.game_results enable row level security;

drop policy if exists "public read seasons" on public.seasons;
drop policy if exists "public read players" on public.players;
drop policy if exists "public read games" on public.games;
drop policy if exists "public read results" on public.game_results;
drop policy if exists "public insert seasons" on public.seasons;
drop policy if exists "public insert players" on public.players;

create policy "public read seasons" on public.seasons for select to anon,authenticated using (true);
create policy "public read players" on public.players for select to anon,authenticated using (true);
create policy "public read games" on public.games for select to anon,authenticated using (true);
create policy "public read results" on public.game_results for select to anon,authenticated using (true);
create policy "public insert players" on public.players for insert to anon,authenticated with check (length(trim(name)) between 2 and 40);
create policy "public insert seasons" on public.seasons for insert to anon,authenticated with check (length(trim(name)) between 2 and 80);

create or replace function public.record_game(p_season_id bigint,p_played_at date,p_results jsonb)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_game_id bigint;v_count integer;v_distinct_players integer;v_distinct_positions integer;v_min_position integer;v_max_position integer;
begin
  if not exists(select 1 from public.seasons where id=p_season_id) then raise exception 'Temporada no encontrada'; end if;
  v_count:=jsonb_array_length(p_results);
  if v_count<3 or v_count>6 then raise exception 'Una partida debe tener entre 3 y 6 jugadores'; end if;
  select count(distinct (r->>'player_id')::bigint),count(distinct (r->>'position')::integer),min((r->>'position')::integer),max((r->>'position')::integer) into v_distinct_players,v_distinct_positions,v_min_position,v_max_position from jsonb_array_elements(p_results) r;
  if v_distinct_players<>v_count then raise exception 'No puede haber jugadores repetidos'; end if;
  if v_distinct_positions<>v_count or v_min_position<>1 or v_max_position<>v_count then raise exception 'Las posiciones deben ser consecutivas de 1 a %',v_count; end if;
  if exists(select 1 from jsonb_array_elements(p_results) r where not exists(select 1 from public.players p where p.id=(r->>'player_id')::bigint)) then raise exception 'Uno de los jugadores no existe'; end if;
  insert into public.games(season_id,played_at,player_count) values(p_season_id,coalesce(p_played_at,current_date),v_count) returning id into v_game_id;
  insert into public.game_results(game_id,player_id,position,victory_points) select v_game_id,(r->>'player_id')::bigint,(r->>'position')::integer,nullif(r->>'victory_points','')::integer from jsonb_array_elements(p_results) r;
  return v_game_id;
end;$$;

revoke all on function public.record_game(bigint,date,jsonb) from public;
grant execute on function public.record_game(bigint,date,jsonb) to anon,authenticated;
grant select on public.seasons,public.players,public.games,public.game_results to anon,authenticated;
grant select on public.game_result_scores,public.season_standings,public.all_time_standings to anon,authenticated;
grant insert on public.players,public.seasons to anon,authenticated;

-- The historical workbook supplies the real seasons; no artificial season is inserted here.
