-- CATAN AMIGOS — Supabase schema
-- Shared, mobile-first league tracker.
-- Score Amigos = (player_count - final_position) × multiplier.
-- 3 players = 1.0 | 4 = 1.2 | 5 = 1.3 | 6 = 1.5

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null unique,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  played_at date not null default current_date,
  player_count integer not null check (player_count between 3 and 6),
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  position integer not null check (position between 1 and 6),
  created_at timestamptz not null default now(),
  unique (game_id, player_id),
  unique (game_id, position)
);

create index if not exists games_season_id_idx on public.games(season_id);
create index if not exists games_played_at_idx on public.games(played_at desc);
create index if not exists game_results_game_id_idx on public.game_results(game_id);
create index if not exists game_results_player_id_idx on public.game_results(player_id);

-- Scores are calculated centrally so every device uses exactly the same rules.
create or replace view public.game_result_scores
with (security_invoker = true)
as
select
  gr.id,
  gr.game_id,
  gr.player_id,
  gr.position,
  g.season_id,
  g.played_at,
  g.player_count,
  round(((g.player_count - gr.position) *
    case g.player_count
      when 3 then 1.0
      when 4 then 1.2
      when 5 then 1.3
      when 6 then 1.5
    end)::numeric, 2) as score_amigos,
  case when gr.position = 1 then 1 else 0 end as win
from public.game_results gr
join public.games g on g.id = gr.game_id;

create or replace view public.season_standings
with (security_invoker = true)
as
select
  g.season_id,
  p.id as player_id,
  p.name,
  coalesce(sum(grs.score_amigos), 0)::numeric(10,2) as score_amigos,
  count(grs.id)::integer as games_played,
  coalesce(sum(grs.win), 0)::integer as wins,
  round(avg(grs.position)::numeric, 2) as average_position
from public.game_result_scores grs
join public.games g on g.id = grs.game_id
join public.players p on p.id = grs.player_id
group by g.season_id, p.id, p.name;

-- RLS: the app is intentionally a shared public league. Reads are public.
-- Writes to games/results happen through the validated record_game function.
alter table public.seasons enable row level security;
alter table public.players enable row level security;
alter table public.games enable row level security;
alter table public.game_results enable row level security;

 drop policy if exists "public read seasons" on public.seasons;
 drop policy if exists "public read players" on public.players;
 drop policy if exists "public read games" on public.games;
 drop policy if exists "public read results" on public.game_results;
 drop policy if exists "public insert seasons" on public.seasons;
 drop policy if exists "public insert players" on public.players;
 drop policy if exists "public insert games" on public.games;
 drop policy if exists "public insert results" on public.game_results;

create policy "public read seasons" on public.seasons for select to anon, authenticated using (true);
create policy "public read players" on public.players for select to anon, authenticated using (true);
create policy "public read games" on public.games for select to anon, authenticated using (true);
create policy "public read results" on public.game_results for select to anon, authenticated using (true);

-- Adding a friend is intentionally simple for this private friend-group app.
create policy "public insert players" on public.players for insert to anon, authenticated with check (length(trim(name)) between 2 and 40);
create policy "public insert seasons" on public.seasons for insert to anon, authenticated with check (length(trim(name)) between 2 and 80);

-- Atomic game registration. It validates the player count, unique players,
-- contiguous positions and season before inserting anything.
create or replace function public.record_game(
  p_season_id bigint,
  p_played_at date,
  p_results jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_game_id bigint;
  v_count integer;
  v_distinct_players integer;
  v_distinct_positions integer;
  v_min_position integer;
  v_max_position integer;
  v_player_count integer;
begin
  if not exists (select 1 from public.seasons s where s.id = p_season_id) then
    raise exception 'Temporada no encontrada';
  end if;

  v_count := jsonb_array_length(p_results);
  if v_count < 3 or v_count > 6 then
    raise exception 'Una partida debe tener entre 3 y 6 jugadores';
  end if;

  select count(distinct (r->>'player_id')::bigint),
         count(distinct (r->>'position')::integer),
         min((r->>'position')::integer),
         max((r->>'position')::integer)
    into v_distinct_players, v_distinct_positions, v_min_position, v_max_position
  from jsonb_array_elements(p_results) r;

  if v_distinct_players <> v_count then
    raise exception 'No puede haber jugadores repetidos';
  end if;

  if v_distinct_positions <> v_count or v_min_position <> 1 or v_max_position <> v_count then
    raise exception 'Las posiciones deben ser consecutivas de 1 a %', v_count;
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_results) r
    where not exists (
      select 1 from public.players p where p.id = (r->>'player_id')::bigint
    )
  ) then
    raise exception 'Uno de los jugadores no existe';
  end if;

  v_player_count := v_count;

  insert into public.games(season_id, played_at, player_count)
  values (p_season_id, coalesce(p_played_at, current_date), v_player_count)
  returning id into v_game_id;

  insert into public.game_results(game_id, player_id, position)
  select
    v_game_id,
    (r->>'player_id')::bigint,
    (r->>'position')::integer
  from jsonb_array_elements(p_results) r;

  return v_game_id;
end;
$$;

revoke all on function public.record_game(bigint, date, jsonb) from public;
grant execute on function public.record_game(bigint, date, jsonb) to anon, authenticated;

grant select on public.seasons, public.players, public.games, public.game_results to anon, authenticated;
grant select on public.game_result_scores, public.season_standings to anon, authenticated;
grant insert on public.players, public.seasons to anon, authenticated;

-- A sensible first season. Safe to run repeatedly.
insert into public.seasons(name, is_active)
select 'Temporada 2026', true
where not exists (select 1 from public.seasons);
